version: '3.8'

services:
  db:
    image: mongo:6.0.5
    container_name: db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    command: mongod --replSet rs0

  mongo-dashboard:
    image: mongo-express
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://localhost:27017/thullo

volumes:
  mongo: